Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
TypeError: __init__() got an unexpected keyword argument 'name'
